### ISSUE TITLE
[Bug] - Virtual enchanting table doesn't load.

### ISSUE THREAD

**Issue by mibby** [Siguza/VirtualPack#24]
@Siguza 

VirtualPack dev 129
http://ci.siguza.net/job/VirtualPack/129/

Spigot 1.8 git-Spigot-6ee12f6-33d5de3 (Latest compile as of 02/26)

```
  enchanttable:
    multiply: '1'
    buy: '0'
    use: '0'
    book: '0'
    cooldown: '0'
```

When trying to use the virtual enchanting table with /ench, it does not load any enchanting options. Using lapis lazuli and a non-enchanted tool.

![link](http://i.imgur.com/yZb7MOD.png)
