### ISSUE TITLE
[Bug] - Virtual furnace smelts but does not show progress.

### ISSUE THREAD

**Issue by mibby** [Siguza/VirtualPack#26]
@Siguza 

VirtualPack dev 129
http://ci.siguza.net/job/VirtualPack/129/

Spigot 1.8 git-Spigot-6ee12f6-33d5de3 (Latest compile as of 02/26)

```
  furnace:
    max: '1'
    start: '0'
    multiply: '0'
    buy: '0'
    use: '0'
    link: '9999999999'
    cooldown: '0'
```
```
tick:
  interval: '30'
```

![link](http://i.imgur.com/w7bIG53.png)

Virtual furnace smelts but does not show arrow progress.
